### ISSUE TITLE
on uninstall, run "Stop Debian"

### ISSUE THREAD

**Issue by eighthave** [guardianproject/lildebi#139]
run "stop debian" on Lil' Debi uninstall to make sure things are left in a sane state.  Also, on fresh install, Lil' Debi will not properly detect a running install on internal storage, and instead thinks there is no install.

**Comment by SDkie** [comment]
How about a kill-debian.sh script ?

**Comment by eighthave** [comment]
yeah, sounds like that might be necessary.
