### ISSUE TITLE
groupadd: failure to write changes /etc/group

### ISSUE THREAD

**Issue by trysten** [guardianproject/lildebi#147]
i can edit the /etc/group file by hand using 'nano /etc/group' but the commands groupadd and addgroup do not work. this is messing with some packages, but i think the problem lies somewhere around groupadd. i don't know what information to post yet, please advise.

**Comment by trysten** [comment]
[output of mount](http://paste.debian.net/142994/)

**Comment by eighthave** [comment]
are there any error messages?  Check your Install Log and see if there are any errors there.

**Comment by trysten** [comment]
i was using debian-kit, not lildebi. switching to lildebi
