### ISSUE TITLE
add /sd-ext to mounted filesystems

### ISSUE THREAD

**Issue by jkk88** [guardianproject/lildebi#151]
Hi, sometimes it is used second partition on sd card, which is named /sd-ext.
Please add test_mount_bind /sd-ext to $app_bin/start-debian.sh

**Comment by eighthave** [comment]
Its easy to add. can you tell me which device/ROM does this?  I like to keep track of where those paths are coming from.

**Comment by jkk88** [comment]
This is used by mod when internal storage to small. It is used for ex. by
mounts2sd app.
