### ISSUE TITLE
Direct links to the images?

### ISSUE THREAD

**Issue by gerroon** [guardianproject/lildebi#162]
Hi

it would be great if you could provide direct links to the downloadable images. There is only Squeeze listed and it is very old.

I just downloaded the latest dev version and tried to download and install jessie and it is failing. I just want to make sure that I can try it with a manually downloaded version. It looks like it could not download the jessie image from the given url.

http://paste.debian.net/154190/

thanks

**Comment by eighthave** [comment]
Lil' Debi is meant to be Debian installer not a manager of pre-cooked images.  It will work with pre-cooked images, but I'm not going to maintain any.  Any of the other pre-cooked images for other Android chroot apps should also work in Lil' Debi.  https://github.com/meefik/linuxdeploy works that way, and I think also features in-app image downloads.
