### ISSUE TITLE
generate /etc/passwd and /etc/group from Android data

### ISSUE THREAD

**Issue by eighthave** [guardianproject/lildebi#33]
In Android each app runs as its own user and has its own group.  This information is listed in `/data/system/packages.list.`  When starting Debian, Lil Debi should generate /etc/passwd and /etc/group from this file.

**Comment by trysten** [comment]
these commands do not work on my distro. something is wrong with groupadd and addgroup.. i can edit /etc/group by hand just find.

**Comment by eighthave** [comment]
Adding the Android Permissons as groups is now being handled by the [`android-permissions`](https://packages.debian.org/android-permissions) package in Debian.  It is included in Lil' Debi and automatically installed on all new installs.

@Alexander-- `android-androresolv` is now [included in Debian](https://packages.debian.org/search?keywords=android-androresolv).  I'd love to see your idea implemented, all of the GNU/Linux installer apps on Android would benefit from that.  My guess is that it would be possible to do as a Debian daemon implemented in Java.  The Android SDK is also now partially [included in Debian](https://packages.debian.org/source/androidsdk-tools).

@trysten could you open a new issue about your issue, and include as much detail as possible, including any error messages, how your Lil' Debi setup, etc.  Also, check the Install Log for errors, and post anything you think is relevant.
