### ISSUE TITLE
Using SuperSU, Lil' Debi never notices when Debian is mounted

### ISSUE THREAD

**Issue by jfmcbrayer** [guardianproject/lildebi#85]
Installation works fine, and mounting the chroot and starting services actually works fine. However, the 'Start Debian' button never changes to 'Stop Debian', or whatever it's supposed to change to. The status line reads "Debian not mounted".

I suspect this has something to do with process-private mounts, as a separately started root terminal can't see any contents in /debian, but this is a WAG on my part.

**Comment by madhungarian** [comment]
So I can't work around this using these steps. I have SuperSU and CWM Superuser install. I've unchecked the Mount namespace separation. I can 'start debian' from lildebi, but when I run the Terminal Emulator and su, the /debian is still empty. What am I missing?
